version: '3.8'

x-rails-base: &rails-base
  build:
    context: .
    dockerfile: Dockerfile
  working_dir: /app
  volumes:
    - .:/app:delegated
    - bundle:/usr/local/bundle

services:
  db:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '63306:3306'
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: 'Asia/Tokyo'
    cap_add:
      - SYS_NICE
    networks:
      - default
  app:
    <<: *rails-base
    tty: true
    stdin_open: true
    command: /bin/sh -c 'rm -f tmp/pids/server.pid && bundle exec ./bin/rails server -p 3000 -b 0.0.0.0'
    ports:
      - "3000:3000"

volumes:
  bundle:
  db:
