version: '3.8'

x-rails-base: &rails-base
  build:
    context: .
    dockerfile: Dockerfile
  working_dir: /app
  volumes:
    - .:/app:delegated
    - bundle:/usr/local/bundle

services:
  app:
    <<: *rails-base
    tty: true
    stdin_open: true
    command: /bin/sh -c 'rm -f tmp/pids/server.pid && bundle exec ./bin/rails server -p 3000 -b 0.0.0.0'
    ports:
      - "3000:3000"

volumes:
  bundle:
