default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password: password

development:
  <<: *default
  host: localhost
  database: app_development

test:
  <<: *default
  host: localhost
  database: app_test
